name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Yarn
      uses: Borales/actions-yarn@master
      with:
        version: 10.x
    - name: yarn install & lint
      run: |
        yarn --skip-integrity-check
        yarn lint

    - name: Build Release
      if: github.ref == 'refs/heads/master'
      run: |
        yarn dist

    - name: GH Pages Publish
      uses: maxheld83/ghpages@v0.2.1
      if: github.ref == 'refs/heads/master'
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        BUILD_DIR: "dist/"
